spring:
  redis:
  # Redis数据库索引（默认为0）
    database: 0  
  # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8  
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: 5000 
  # 连接池中的最大空闲连接
    pool.max-idle: 8  
  # 连接池中的最小空闲连接
    pool.min-idle: 0  
  # 连接超时时间（毫秒）
    timeout: 0
    #    cluster:
    nodes:
      127.0.0.1:6379
      #- 192.168.1.101:6379
      #- 192.168.1.102:6379
      #- 192.168.1.107:6379
      #- 192.168.1.108:6379
      #- 192.168.1.109:6379
      #- 192.168.1.110:6379
  rocketmq:
    consumer: 
      namesrv-addr: 127.0.0.1:9876 #192.168.1.113:9876;192.168.1.114:9876
      group-name: account-consumer
      topic: account
      check-keys: check
      consume-failure-retry-times: 3
    producer:
      namesrv-addr: 127.0.0.1:9876 #192.168.1.113:9876;192.168.1.114:9876
      group-name: account-transaction-message-producer
      topic: account-check
#多数据源 1主2从
datasource:
 #从库数量
  readSize: 2
   # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
#主库
  write:
    url: jdbc:mysql://127.0.0.1:3306/eshop_order?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 10
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  read1:
    url: jdbc:mysql://127.0.0.1:3306/eshop_order?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  read2:
    url: jdbc:mysql://127.0.0.1:3306/eshop_order?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
